import type { Metadata } from "next";
import { Roboto_Flex, Nunito_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { OrderPreferenceProvider } from "@/context/OrderPreferenceContext";
import ChangeAddress from "@/components/Locator/ChangeAddress";
import Locator from "@/components/Locator";
import NearestStores from "@/components/Locator/NearestStores";

const roboto = Roboto_Flex({
  variable: "--font-roboto",
  subsets: ["latin"],
});

const nunito = Nunito_Sans({
  variable: "--font-nunito",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${nunito.variable} ${roboto.variable} antialiased relative overflow-x-hidden`}
      >
        <OrderPreferenceProvider>
          <Navbar />
          <Locator />
          <ChangeAddress />
          <NearestStores />
          {children}
        
        </OrderPreferenceProvider>
      </body>
    </html>
  );
}
