import type { Metadata } from "next";
import { Roboto_Flex, Nunito_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { OrderPreferenceProvider } from "@/context/OrderPreferenceContext";
import { CartProvider } from "@/context/CartContext";
import { CheckoutProvider } from "@/context/CheckoutContext";
import ChangeAddress from "@/components/Locator/ChangeAddress";
import Locator from "@/components/Locator";
import NearestStores from "@/components/Locator/NearestStores";
import OrderPreferenceDisplay from "@/components/OrderPreferenceDisplay";
import CartDisplay from "@/components/CartDisplay";

const roboto = Roboto_Flex({
  variable: "--font-roboto",
  subsets: ["latin"],
});

const nunito = Nunito_Sans({
  variable: "--font-nunito",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${nunito.variable} ${roboto.variable} antialiased relative min-h-screen overflow-visible`}
      >
        <OrderPreferenceProvider>
          <CartProvider>
            <CheckoutProvider>
              <OrderPreferenceDisplay />
              <Navbar />
              <Locator />
              <ChangeAddress />
              <NearestStores />
              <CartDisplay />
              {children}
            </CheckoutProvider>
          </CartProvider>
        </OrderPreferenceProvider>
      </body>
    </html>
  );
}
